main/urls.py
from django.urls import path
from main.views import add_product_ajax, create_product_flutter, delete_product_ajax, get_product_json, show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id, register,login_user, logout_user, delete_product, add_product, sub_product, edit_product 

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('delete_product/<int:id>', delete_product, name='delete_product'),
    path('add_product/<int:id>', add_product, name='add_product'),
    path('sub_product/<int:id>', sub_product, name='sub_product'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete_product_ajax/<int:id>', delete_product_ajax, name='delete_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

maribelanja/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)   # UPDATED!
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    price = models.IntegerField()
    amount = models.IntegerField(null = True)
    description = models.TextField()

# Create your models here.

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "amount", "description"]

main/views.py
import json
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from main.forms import ProductForm
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from main.models import Product
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.views.decorators.csrf import csrf_exempt

@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)
    total_produk = products.count()
    context = {
        'name': request.user.username, # Nama kamu
        'total_produk': total_produk,
        'products': products,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/login')
def delete_product(request, id):
    products = Product.objects.filter(user=request.user).filter(pk=id)
    products.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

@login_required(login_url='/login')
def add_product(request, id):
    products = Product.objects.filter(user=request.user).filter(pk=id).first()
    products.amount += 1
    products.save()
    return HttpResponseRedirect(reverse("main:show_main")) 

@login_required(login_url='/login')
def sub_product(request, id):
    products = Product.objects.filter(user=request.user).filter(pk=id).first()
    if products.amount > 0:
        products.amount -= 1
        products.save()
    return HttpResponseRedirect(reverse("main:show_main")) 

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def get_product_json(request):
    product_item = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(name=name, price=price, amount = amount, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def delete_product_ajax(request, id):
    products = Product.objects.filter(user=request.user).filter(pk=id)
    products.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            amount = int(data["amount"]),
            description = data["description"],
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="bg-green-200 p-4">
    <h1 class="text-2xl font-semibold">Edit Product</h1>

    <form method="POST">
        {% csrf_token %}
        <table class="mt-4">
            {{ form.as_table }}
            <tr>
                <td></td>
                <td>
                    <input class="bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-600 transition duration-300 cursor-pointer" type="submit" value="Edit Product"/>
                </td>
            </tr>
        </table>
    </form>
</div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<div class="min-h-screen flex items-center justify-center bg-green-200">
    <div class="max-w-md w-full bg-white p-8 space-y-4 rounded-lg shadow-md">
        <h1 class="text-4xl font-semibold">Login - Mari Belanja</h1>
        
        <form method="POST" action="">
            {% csrf_token %}
            <div class="space-y-3">
                <label for="username" class="block text-sm font-medium text-gray-800">Username:</label>
                <input type="text" name="username" id="username" placeholder="Username" class="w-full border rounded-md px-3 py-2" />
            </div>
            
            <div class="space-y-2">
                <label for="password" class="block text-sm font-medium text-gray-800">Password:</label>
                <input type="password" name="password" id="password" placeholder="Password" class="w-full border rounded-md px-3 py-2" />
            </div>

            <div class="mt-5">
                <input type="submit" value="Login" class="w-full bg-green-500 text-white font-semibold rounded-md py-2 hover:bg-green-600 transition duration-300 cursor-pointer" />
            </div>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li class="text-red-500">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <p class="mt-3">Don't have an account yet? <a href="{% url 'main:register' %}" class="text-blue-500 hover:underline">Register Now</a></p>
    </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg" style="background-color: #A7F3D0;">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Mari Belanja</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Penjualan</a>
          </li>
        </ul>
        <a class="d-flex mr-4" href="#">log in as {{name}}</a>
        <form class="d-flex" action="{% url 'main:logout' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-outline-success" type="submit">Logout</button>
        </form>
      </div>
    </div>
  </nav>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  <form id="form" onsubmit="return false;">
                      {% csrf_token %}
                      <div class="mb-3">
                          <label for="name" class="col-form-label">Name:</label>
                          <input type="text" class="form-control" id="name" name="name"></input>
                      </div>
                      <div class="mb-3">
                          <label for="price" class="col-form-label">Price:</label>
                          <input type="number" class="form-control" id="price" name="price"></input>
                      </div>
                      <div class="mb-3">
                        <label for="amount" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount"></input>
                    </div>
                      <div class="mb-3">
                          <label for="description" class="col-form-label">Description:</label>
                          <textarea class="form-control" id="description" name="description"></textarea>
                      </div>
                  </form>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
              </div>
          </div>
      </div>
  </div>
  
  <br />

  <div id="product_cards" class="all-product d-flex flex-wrap align-content-start gap-4"></div>


  <button type="button" class="bg-green-500 text-white px-2 py-1 rounded-lg hover:bg-green-600 transition duration-300" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product</button>

  <script>
      async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
    }

      async function refreshProducts() {
        document.getElementById("product_cards").innerHTML = ""
        const products = await getProducts()
        let htmlString = `
        <div class="container mx-auto mt-4">
            <h1 class="text-3xl font-semibold">Welcome {{name}}!</h1>
            <h4 class="mt-4">Products: ${products.length}</h4>
          </div>
        `
        products.forEach((item) => {
            htmlString += `\n
            <div class="card" style="width: 15 rem; height: 220px; background-color: #96CCA8; padding: 20px; margin: 20px; border: 1px solid #000;">
                <div class="card-body">
                  <h4 class="card-title" style="background-color: white; color: black; padding: 5px; border-radius: 10px; display: inline-block;">${item.fields.name}</h4>
                    <p class="card-harga">Rp. ${item.fields.price}</p>
                    <p class="card-stok">
                      <a href="sub_product/${item.pk}">
                            <button class="bg-green-500 text-white px-2 py-1 rounded-lg hover:bg-blue-600 transition duration-300">-</button>
                        </a>
                        ${item.fields.amount}
                        <a href="add_product/${item.pk}">
                            <button class="bg-green-500 text-white px-2 py-1 rounded-lg hover:bg-blue-600 transition duration-300">+</button>
                        </a> 
                     </p>
                    <p class="card-text">${item.fields.description}</p>
                    <a href='edit-product/${item.pk}'><button class="bg-green-500 text-white px-2 py-1 rounded-lg hover:bg-green-600 transition duration-300">Edit</button></a>
                    <a href='delete_product/${item.pk}'><button class="bg-black text-white px-2 py-1 rounded-lg hover:bg-red-600 transition duration-300">Delete</button></a>
                </div>
            </div>` 
        })

        document.getElementById("product_cards").innerHTML = htmlString
    }
      refreshProducts()

      function addProduct() {
          fetch("{% url 'main:add_product_ajax' %}", {
              method: "POST",
              body: new FormData(document.querySelector('#form'))
          }).then(refreshProducts)

          document.getElementById("form").reset()
          return false
      }

      function deleteproduct(id){
        fetch("{% url 'main:delete_product_ajax ${id}'}", {
              method: "POST",
              body: new FormData(document.querySelector('#form'))
          }).then(refreshProducts)
          return false

      }
      refreshProducts()
      document.getElementById("button_add").onclick = addProduct
  </script>

    <h5 class="mt-4">Sesi terakhir login: {{ last_login }}</h5>
</div>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<div class="bg-green-200 p-4">
    <h1 class="text-2xl font-semibold">Register - Mari Belanja</h1>  

    <form method="POST">  
        {% csrf_token %}  
        <div class="mt-4">
            {{ form.as_p }}
        </div>  
        <div class="mt-4">
            <button class="bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-600 transition duration-300 cursor-pointer" type="submit" name="submit">Register</button>  
        </div>
    </form>

    {% if messages %}  
        <ul class="mt-4">   
            {% for message in messages %}  
                <li class="text-red-500">{{ message }}</li>  
            {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}